import { Category } from '@/core/domain/transaction.entity';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: 'cat-alimentacao',
    name: 'Alimentação',
    icon: 'Utensils',
    color: '#F59E0B',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-moradia',
    name: 'Moradia & Contas',
    icon: 'Home',
    color: '#3B82F6',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-transporte',
    name: 'Transporte & Carro',
    icon: 'Car',
    color: '#6366F1',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-eletronicos',
    name: 'Eletrônicos & Equipamentos',
    icon: 'Laptop',
    color: '#38BDF8',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-saude',
    name: 'Saúde & Cuidados',
    icon: 'HeartPulse',
    color: '#EC4899',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-lazer',
    name: 'Lazer & Viagem',
    icon: 'Plane',
    color: '#A855F7',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-outros',
    name: 'Outras Despesas',
    icon: 'MoreHorizontal',
    color: '#71717A',
    type: 'expense',
    isSystemDefault: true,
  },
  {
    id: 'cat-salario',
    name: 'Salário & Remuneração',
    icon: 'Briefcase',
    color: '#22C55E',
    type: 'income',
    isSystemDefault: true,
  },
  {
    id: 'cat-proventos',
    name: 'Proventos & Dividendos',
    icon: 'TrendingUp',
    color: '#10B981',
    type: 'income',
    isSystemDefault: true,
  },
  {
    id: 'cat-outras-receitas',
    name: 'Outras Receitas',
    icon: 'Coins',
    color: '#14B8A6',
    type: 'income',
    isSystemDefault: true,
  },
];
